const io = require("../../BaseProjectJS/io")
io.write("Escreva o número da semana")
let a = io.readInt()
if (a === 1) io.write("Domingo")
if (a === 2) io.write("Segunda")
if (a === 3) io.write("Terça")
if (a === 4) io.write("Quarta")
if (a === 5) io.write("Quinta")
if (a === 6) io.write("Sexta")
if (a === 7) io.write("Sábado")
if (a > 7 || a < 1) io.write("Não é um número válido")